/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import javax.swing.*;
import java.io.FileNotFoundException;

/**
 *
 * @author TheSaddestBread
 */
public class MainApp extends javax.swing.JFrame {
    /**
     /**
     * Creates new form StudentApp
     */
    DataManager studentdata = new DataManager();

    String Username;
    public MainApp(String username) throws Exception {
        Username = username;
        initComponents();
    }
    public void run(int id) throws Exception {
        if(id == 1)
            new StudentApp(Username).setVisible(true);
        if(id == 2)
            new TeacherApp(Username).setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ShellTitle = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        Assignment = new javax.swing.JButton();
        Feedback = new javax.swing.JButton();
        StudentPoll = new javax.swing.JButton();
        logOut = new javax.swing.JButton();
        Home = new javax.swing.JPanel();
        gradesText = new javax.swing.JLabel();
        LargeBody = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        Submit = new javax.swing.JButton();
        Disagree = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        Agree = new javax.swing.JButton();
        TitleText = new javax.swing.JLabel();
        AllSideButtons = new javax.swing.JButton[]{Assignment, Feedback, StudentPoll};

        LargeBody.setVisible(false);
        jTextArea1.setVisible(false);
        TitleText.setVisible(false);
        Agree.setVisible(false);
        Disagree.setVisible(false);
        Submit.setVisible(false);
        gradesText.setVisible(false);
        jTextArea2.setVisible(false);
        jScrollPane2.setVisible(false);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(140, 239, 171));

        jLabel1.setBackground(new java.awt.Color(4, 67, 69));
        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel1.setText("Desire4Learning");

        ShellTitle.setBackground(new java.awt.Color(4, 67, 69));
        ShellTitle.setFont(new java.awt.Font("Tw Cen MT", 0, 48)); // NOI18N
        ShellTitle.setForeground(new java.awt.Color(4, 67, 69));
        ShellTitle.setText("Select a Catagory");
        ShellTitle.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        ShellTitle.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel4.setText(Username);
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel3.setBackground(new java.awt.Color(4, 67, 69));
        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 0, 10)); // NOI18N
        jLabel3.setText("Interactive Education");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ShellTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(0, 19, Short.MAX_VALUE)
                                                .addComponent(jLabel1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel3)
                                                .addGap(43, 43, 43))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel4)))
                                .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(ShellTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.setBackground(new java.awt.Color(51, 68, 67));

        jPanel4.setBackground(new java.awt.Color(51, 68, 67));

        Assignment.setBackground(new java.awt.Color(51, 68, 67));
        Assignment.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        Assignment.setForeground(new java.awt.Color(255, 255, 255));
        Assignment.setText(" Grades ");
        Assignment.setBorder(null);
        Assignment.setBorderPainted(false);
        Assignment.setContentAreaFilled(false);
        Assignment.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Assignment.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        Assignment.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Assignment.setOpaque(true);
        Assignment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    AssignmentActionPerformed(evt);
                } catch (FileNotFoundException e) {
                    e.printStackTrace();
                }
            }
        });

        Feedback.setBackground(new java.awt.Color(51, 68, 67));
        Feedback.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        Feedback.setForeground(new java.awt.Color(255, 255, 255));
        Feedback.setText(" Feedback");
        Feedback.setBorder(null);
        Feedback.setBorderPainted(false);
        Feedback.setContentAreaFilled(false);
        Feedback.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Feedback.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        Feedback.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Feedback.setOpaque(true);
        Feedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    FeedbackActionPerformed(evt);
                } catch (FileNotFoundException e) {
                    e.printStackTrace();
                }
            }
        });

        StudentPoll.setBackground(new java.awt.Color(51, 68, 67));
        StudentPoll.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        StudentPoll.setForeground(new java.awt.Color(255, 255, 255));
        StudentPoll.setText("Student Polls");
        StudentPoll.setBorder(null);
        StudentPoll.setBorderPainted(false);
        StudentPoll.setContentAreaFilled(false);
        StudentPoll.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        StudentPoll.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        StudentPoll.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        StudentPoll.setOpaque(true);
        StudentPoll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    StudentPollActionPerformed(evt);
                } catch (FileNotFoundException e) {
                    e.printStackTrace();
                }
            }
        });

        logOut.setBackground(new java.awt.Color(51, 68, 67));
        logOut.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        logOut.setForeground(new java.awt.Color(255, 255, 255));
        logOut.setText("Log Out ");
        logOut.setBorder(null);
        logOut.setBorderPainted(false);
        logOut.setContentAreaFilled(false);
        logOut.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        logOut.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        logOut.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        logOut.setOpaque(true);
        logOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap(38, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                                .addComponent(logOut, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addContainerGap())
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(StudentPoll)
                                                        .addComponent(Assignment, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        //.addComponent(Schedule, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(Feedback, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(61, 61, 61))))
        );
        jPanel4Layout.setVerticalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(Assignment, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Feedback, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(StudentPoll, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                //.addComponent(Schedule, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(logOut, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );

        Home.setBackground(new java.awt.Color(255, 255, 255));
        Home.setForeground(new java.awt.Color(255, 255, 255));
        Home.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gradesText.setFont(new java.awt.Font("Tw Cen MT", 0, 20)); // NOI18N
        gradesText.setForeground(new java.awt.Color(71, 71, 71));
        gradesText.setText("This is a test! ");
        Home.add(gradesText, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 574, 50));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        LargeBody.setViewportView(jTextArea1);

        Home.add(LargeBody, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 420, 160));

        Submit.setBackground(new java.awt.Color(140, 239, 171));
        Submit.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        Submit.setForeground(new java.awt.Color(51, 68, 67));
        Submit.setText(" Submit");
        Submit.setBorder(null);
        Submit.setBorderPainted(false);
        Submit.setContentAreaFilled(false);
        Submit.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Submit.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        Submit.setOpaque(true);
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    SubmitActionPerformed(evt);
                } catch (FileNotFoundException e) {
                    e.printStackTrace();
                }
            }
        });
        Home.add(Submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 220, 90, 40));

        Disagree.setBackground(new java.awt.Color(140, 239, 171));
        Disagree.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        Disagree.setForeground(new java.awt.Color(51, 68, 67));
        Disagree.setText("Disagree");
        Disagree.setBorder(null);
        Disagree.setBorderPainted(false);
        Disagree.setContentAreaFilled(false);
        Disagree.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Disagree.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        Disagree.setOpaque(true);
        Disagree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    DisagreeActionPerformed(evt);
                } catch (FileNotFoundException e) {
                    e.printStackTrace();
                }
            }
        });
        Home.add(Disagree, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 320, 99, 47));

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jTextArea2.setForeground(new java.awt.Color(74, 74, 74));
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(5);
        jTextArea2.setText("sfdsdfadsfoijadiofsjadiosfjdaiosfhiadsfhadisfhuadsifhadsuifhaduisfadhuifadhuifhaduifdsa");
        jTextArea2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTextArea2.setCaretColor(new java.awt.Color(255, 255, 255));
        jTextArea2.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jScrollPane2.setViewportView(jTextArea2);

        Home.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 560, 230));

        Agree.setBackground(new java.awt.Color(140, 239, 171));
        Agree.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        Agree.setForeground(new java.awt.Color(51, 68, 67));
        Agree.setText(" Agree");
        Agree.setBorder(null);
        Agree.setBorderPainted(false);
        Agree.setContentAreaFilled(false);
        Agree.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Agree.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        Agree.setOpaque(true);
        Agree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    AgreeActionPerformed(evt);
                } catch (FileNotFoundException e) {
                    e.printStackTrace();
                }
            }
        });
        Home.add(Agree, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 320, 99, 47));

        TitleText.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        TitleText.setForeground(new java.awt.Color(28, 28, 28));
        TitleText.setText("This is a test! ");
        Home.add(TitleText, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 21, 560, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, 0)
                                                .addComponent(Home, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Home, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>

    private void logOutActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        System.exit(1);

    }
    void HighlightButton(int id, String title) throws FileNotFoundException {
        ShellTitle.setText(title);
        for(int i = 0; i < AllSideButtons.length; i++)
        {
            if(i == id - 1){
                AllSideButtons[i].setBackground(new java.awt.Color(41, 52, 52));
            }
            else
            {
                AllSideButtons[i].setBackground(new java.awt.Color(51, 68, 67));

            }
        }
    }

    public void AssignmentActionPerformed(java.awt.event.ActionEvent evt) throws FileNotFoundException {
        // TODO add your handling code here:
        int id = 1;
        String title = "Grades";
        HighlightButton(id , title);
        LargeBody.setVisible(false);

    }

    public void SubmitActionPerformed(java.awt.event.ActionEvent evt) throws FileNotFoundException {
        // TODO add your handling code here:
        String input = jTextArea1.getText();
        studentdata.changeFeedback(Username, input);
        Submit.setText("Success!");
    }

    public void StudentPollActionPerformed(java.awt.event.ActionEvent evt) throws FileNotFoundException {
        // TODO add your handling code here:
        int id = 3;
        String title = "Student Polls";
        HighlightButton(id , title);

    }

    public void FeedbackActionPerformed(java.awt.event.ActionEvent evt) throws FileNotFoundException {
        // TODO add your handling code here:
        int id = 2;
        String title = "Feedback";
        HighlightButton(id , title);
    }

    public void DisagreeActionPerformed(java.awt.event.ActionEvent evt) throws FileNotFoundException {
        // TODO add your handling code here:
        studentdata.pollDisgree(Username);
        Agree.setText("Agree");
        Disagree.setText("Submitted");
    }

    public void AgreeActionPerformed(java.awt.event.ActionEvent evt) throws FileNotFoundException {
        // TODO add your handling code here:
        studentdata.pollAgree(Username);
        Disagree.setText("Disagree");
        Agree.setText("Submitted!");
    }

    // Variables declaration - do not modify
    public javax.swing.JButton Agree;
    public javax.swing.JButton Assignment;
    public javax.swing.JButton Disagree;
    public javax.swing.JButton Feedback;
    public javax.swing.JPanel Home;
    public javax.swing.JScrollPane LargeBody;
    public javax.swing.JButton StudentPoll;
    public javax.swing.JButton Submit;
    public javax.swing.JLabel gradesText;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel ShellTitle;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel TitleText;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    public javax.swing.JPanel jPanel4;
    public javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTextArea jTextArea1;
    public javax.swing.JTextArea jTextArea2;
    public javax.swing.JButton logOut;

    public javax.swing.JButton[] AllSideButtons;
    // End of variables declaration
}
